library(RSelenium)


startServer()
remDr <- remoteDriver(browserName = 'chrome')
remDr$open()
remDr$navigate('https://trends.google.com/trends/explore?date=2019-10-01%202020-03-29&q=%2Fm%2F0cycc,%2Fm%2F01cpyy,COVID')

testit <- function(x)
{
  p1 <- proc.time()
  Sys.sleep(x)
  proc.time() - p1 # The cpu usage should be negligible
}


(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[1]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)
Afghanistan <- remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[2]')
Afghanistan$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)
Aland_Island <- remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[3]')
Aland_Island$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[1]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)
Albania <- remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[4]')
Albania$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)  
Algeria <- remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[5]')
Algeria$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)
American_Samoa <- remDr$findElement(using = 'xpath', '//*[@id="ul-12"]/li[6]')
American_Samoa$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)
Andorra <- remDr$findElement(using = 'xpath', '//*[@id="ul-12"]/li[7]')
Andorra$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

country <- remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]')
country$clickElement()
testit(1)
Angola <- remDr$findElement(using = 'xpath', '//*[@id="ul-12"]/li[8]')
Angola$clickElement()
download <- remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i')
download$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)

(remDr$findElement(using = 'xpath', '//*[@id="compare-pickers-wrapper"]/div/hierarchy-picker[1]/ng-include/div[1]'))$clickElement()
testit(1)
(remDr$findElement(using = 'xpath', '//*[@id="ul-8"]/li[9]'))$clickElement()
(remDr$findElement(using = 'xpath', '/html/body/div[2]/div[2]/div/md-content/div/div/div[2]/trends-widget/ng-include/widget/div/div/div/widget-actions/div/button[1]/i'))$clickElement()
testit(1)


